[versions]
logback = "1.5.7"
tg-bot = "7.1.0"
ksp = "2.0.10-1.0.24"

kotlin = "2.0.10"

[libraries]
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
telegram-bot = { id = "eu.vendeli.telegram-bot", version.ref = "tg-bot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }