[versions]
spring-boot = "3.3.2"
spring-dependency-management = "1.1.6"
tg-bot = "7.2.2"
ksp = "2.0.10-1.0.24"

kotlin = "2.0.10"

[libraries]
tg-spring-starter = { module = "eu.vendeli:spring-ktgram-starter", version.ref = "tg-bot" }

[plugins]
telegram-bot = { id = "eu.vendeli.telegram-bot", version.ref = "tg-bot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }

